tasks:

- source: tasks/data-loading.ipynb
  product:
    path_to_dir: output/data-loading-path_to_dir.pkl
    nb: output/data-loading.ipynb

- source: tasks/parsing-jsons-into-a-data-frame.ipynb
  product:
    df: output/parsing-jsons-into-a-data-frame-df.pkl
    nb: output/parsing-jsons-into-a-data-frame.ipynb

- source: tasks/artists.ipynb
  product:
    nb: output/artists.ipynb

- source: tasks/tags.ipynb
  product:
    df_tagged: output/tags-df_tagged.pkl
    df: output/tags-df.pkl
    nb: output/tags.ipynb

- source: tasks/tracks-tagged-as-rock-.ipynb
  product:
    nb: output/tracks-tagged-as-rock-.ipynb
